blank_issues_enabled: true
contact_links:
  - name: 🐞 Bug v6
    url: https://github.community/c/software-development/47
    about: Find/file tickets with the community
  - name: ⭐️ Feature Request
    url: https://github.com/npm/feedback
    about: Add your request or discuss the project w/ the community
  - name: 📃 RFC
    url: https://github.com/npm/rfcs
    about: Create a more formal proposal/idea via our RFC
  - name: 🚥 Registry Status
    url: https://status.npmjs.org
    about: Check the current status of the website/registry
  - name: 🗂 Documentation
    url: https://docs.npmjs.com
    about: Preview our new docs
  - name: 📫 Support
    url: https://www.npmjs.com/support
    about: Contact npm support staff with problems requiring human intervention
